const LAYOUT_STYLE = `<style id="coach-layout-polish-style">
.brand-title{display:inline-flex;align-items:center;justify-content:center;gap:10px;white-space:normal}.brand-title-logo{width:42px;height:42px;display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto}.brand-title-logo svg{width:100%;height:100%;display:block}.accordion-chevron{flex:0 0 36px!important;width:36px!important;height:36px!important;margin-left:10px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;color:transparent!important;font-size:0!important;line-height:1!important;position:relative!important;transform:rotate(0deg);transform-origin:center;transition:transform .25s ease}.accordion-chevron::before{content:"";width:15px;height:15px;border-right:3px solid #1f5f3b;border-bottom:3px solid #1f5f3b;border-radius:2px;transform:rotate(45deg) translate(-1px,-1px);box-sizing:border-box}details[open]>.accordion-header .accordion-chevron{transform:rotate(180deg)}
.container>.card:first-of-type{padding:0!important;border-radius:10px!important;margin:0 0 12px!important;box-shadow:0 2px 8px rgba(0,0,0,.14)!important;overflow:hidden!important}.container>.card:first-of-type .beheer-summary{min-height:50px!important;margin:0!important;padding:0 14px!important;font-size:20px!important;line-height:1.15!important;display:flex!important;align-items:center!important;box-sizing:border-box!important}.container>.card:first-of-type details>div{padding:8px 12px 10px!important;margin-top:0!important}.container>.card:first-of-type input{padding:8px 10px!important;margin-top:4px!important;margin-bottom:7px!important;font-size:15px!important}.container>.card:first-of-type button{min-height:36px!important;padding:7px 11px!important;font-size:14px!important;border-radius:8px!important}.premium-feature.trainer-club-feature[open]{overflow:visible!important}.premium-feature.trainer-club-feature[open] .premium-body{max-height:none!important;overflow:visible!important;display:grid;gap:12px}.video-analysis-sectie,.video-analyse-sectie{margin-top:12px!important}.video-analysis-accordion{border-color:#d2e7db!important}.video-analysis-accordion:not([open]) .video-analysis-paneel{display:none!important}.video-analysis-paneel{gap:12px!important;overflow:visible!important}.player-video-separator{margin:24px 0 12px!important;border:0!important;border-top:1px solid #b7c7be!important;height:0!important}.pro-later-badge{display:inline-flex!important;align-items:center!important;justify-content:center!important;white-space:nowrap!important;padding:2px 7px!important;border-radius:999px!important;background:#f3ecff!important;color:#6e2bd8!important;font-size:9px!important;font-weight:800!important;letter-spacing:.04em!important;line-height:1.2!important;text-transform:uppercase!important}.youtube-sync-area{position:relative;margin-top:24px!important;padding-top:12px!important;border:0!important;border-radius:0!important;background:transparent!important}.youtube-sync-area::before{content:"";position:absolute;top:0;left:0;right:0;height:1px;background:#b7c7be}.youtube-sync-area .sync-accordion{border:1px solid #d2e7db!important;border-radius:12px!important;background:#f7fcf9!important;overflow:hidden!important}
#manageVideosAccordion>.accordion-header,#manageVideosAccordion>summary,.youtube-sync-area .sync-accordion>.accordion-header,.youtube-sync-area .sync-accordion>summary{display:grid!important;grid-template-columns:minmax(0,1fr) auto 36px!important;column-gap:10px!important;align-items:center!important;min-height:66px!important;padding:15px 16px!important;box-sizing:border-box!important}#manageVideosTitle,.youtube-sync-area .accordion-title{font-family:inherit!important;font-size:18px!important;font-weight:700!important;line-height:1.2!important;color:#1f5f3b!important;letter-spacing:0!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;margin:0!important;padding:0!important;min-width:0!important}.premium-feature.trainer-club-feature summary .pro-later-badge,.sync-accordion summary .pro-later-badge{justify-self:end!important;align-self:center!important}.knopgroep{gap:12px!important;align-items:center!important}.knopgroep button{margin:0!important;min-height:44px!important;border-radius:9px!important;white-space:nowrap!important}.player-box .knopgroep.hidden-during-recording.recording-state-recorded{display:flex!important;flex-direction:row!important;flex-wrap:wrap!important;align-items:center!important}.player-box .knopgroep.hidden-during-recording .help-icon{display:none!important}.player-box .knopgroep.hidden-during-recording button[onclick*="stopOpname"],.player-box .knopgroep.hidden-during-recording button[onclick*="wisLeerlingVideo"],.player-box .knopgroep.hidden-during-recording .recording-stop-button,.player-box .knopgroep.hidden-during-recording .recording-clear-button{display:none!important}.player-box .knopgroep.hidden-during-recording.recording-state-recorded button[onclick*="stopOpname"],.player-box .knopgroep.hidden-during-recording.recording-state-recorded button[onclick*="wisLeerlingVideo"],.player-box .knopgroep.hidden-during-recording.recording-state-recorded .recording-stop-button,.player-box .knopgroep.hidden-during-recording.recording-state-recorded .recording-clear-button{display:inline-flex!important}.player-box .knopgroep.hidden-during-recording.recording-state-recording button[onclick*="startOpname"],.player-box .knopgroep.hidden-during-recording.recording-state-recording button[onclick*="wisLeerlingVideo"],.player-box .knopgroep.hidden-during-recording.recording-state-recording .recording-start-button,.player-box .knopgroep.hidden-during-recording.recording-state-recording .recording-clear-button{display:none!important}.player-box .knopgroep.hidden-during-recording.recording-state-recording button[onclick*="stopOpname"],.player-box .knopgroep.hidden-during-recording.recording-state-recording .recording-stop-button{display:inline-flex!important}.recording-stop-button{background:#a3261f!important}.recording-ready-button{background:#1f5f3b!important}.recording-new-button{background:#17482d!important}
.bewaar-regel{display:flex!important;gap:10px!important;align-items:center!important;flex-wrap:wrap!important}.bewaar-regel button:not(.help-icon){margin:0!important;min-height:42px!important}.bewaar-regel .help-icon{position:static!important;transform:none!important;flex:0 0 30px!important;width:30px!important;height:30px!important;min-width:30px!important;min-height:30px!important;margin:0!important;padding:0!important;border-radius:50%!important;background:#fff!important;color:#1f5f3b!important;border:2px solid #1f5f3b!important;line-height:1!important;box-sizing:border-box!important}.download-video-bestand-knop{background:#17482d!important}.storage-choice-note{display:none!important}.upload-loaded-note,.button-local-message,.storage-inline-help{max-width:min(380px,calc(100vw - 40px))!important;margin:6px 0 2px!important;padding:10px 12px!important;border-left:5px solid #d6a800!important;border-radius:10px!important;background:#fff8d8!important;color:#1f5f3b!important;font-size:15px!important;font-weight:700!important;line-height:1.35!important;box-shadow:0 2px 8px rgba(0,0,0,.12)!important;box-sizing:border-box!important}
.analyse-controls,.sessie-sectie{display:flex!important;flex-direction:column!important;align-items:flex-start!important;gap:10px!important;width:100%!important;max-width:100%!important;overflow:visible!important}.analysis-aligned-button,.session-aligned-button{width:auto!important;max-width:calc(100vw - 74px)!important;min-height:44px!important;display:inline-flex!important;align-items:center!important;justify-content:flex-start!important;box-sizing:border-box!important;margin:0!important;padding-left:18px!important;padding-right:18px!important;white-space:nowrap!important;text-align:left!important;flex:0 0 auto!important}.analysis-help-row,.session-help-row{display:inline-flex!important;align-items:center!important;justify-content:flex-start!important;gap:8px!important;width:auto!important;max-width:100%!important;box-sizing:border-box!important;overflow:visible!important;flex-wrap:nowrap!important}.analysis-help-row .help-icon,.session-help-row .help-icon{position:static!important;transform:none!important;flex:0 0 30px!important;width:30px!important;height:30px!important;min-width:30px!important;min-height:30px!important;margin:0!important;padding:0!important;border-radius:50%!important;box-sizing:border-box!important;background:#fff!important;color:#1f5f3b!important;border:2px solid #1f5f3b!important}.session-action-stack{display:flex!important;flex-direction:column!important;align-items:flex-start!important;gap:10px!important;width:100%!important}.player-scrub-panel{position:relative;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;margin:10px 0 4px;padding:10px 12px;border-radius:12px;background:#eef7f1;color:#1f5f3b;font-weight:bold}.player-scrub-time{font-variant-numeric:tabular-nums;font-size:15px;min-width:44px;text-align:center}.player-scrub-slider{width:100%;height:28px;margin:0!important;padding:0!important;accent-color:#1f5f3b;cursor:pointer}.ai-marker-layer{position:absolute;inset:0;pointer-events:none}.ai-scrub-marker{position:absolute;width:13px!important;height:13px!important;min-width:13px!important;min-height:13px!important;padding:0!important;margin:0!important;border-radius:50%!important;border:2px solid #fff!important;box-shadow:0 1px 5px rgba(0,0,0,.35)!important;transform:translate(-50%,-50%)!important;pointer-events:auto!important;cursor:pointer!important;z-index:4!important}.ai-scrub-marker.attention{background:#e08a17!important}.ai-scrub-marker.error{background:#c7352d!important}.melding{top:18px!important;left:auto!important;right:156px!important;transform:none!important;max-width:min(360px,calc(100vw - 32px))!important;text-align:center!important;box-sizing:border-box!important}
@media(max-width:760px){.melding{top:12px!important;left:16px!important;right:16px!important;max-width:none!important}}@media(max-width:700px){.brand-title{gap:7px}.brand-title-logo{width:34px;height:34px}.container>.card:first-of-type .beheer-summary{min-height:48px!important;padding:0 12px!important;font-size:18px!important}.container>.card:first-of-type{border-radius:9px!important;margin-bottom:10px!important}.player-video-separator{margin:14px 0 12px!important}.youtube-sync-area{margin-top:14px!important}#manageVideosAccordion>.accordion-header,#manageVideosAccordion>summary,.youtube-sync-area .sync-accordion>.accordion-header,.youtube-sync-area .sync-accordion>summary{min-height:62px!important;padding:13px 14px!important}#manageVideosTitle,.youtube-sync-area .accordion-title{font-size:17px!important}.pro-later-badge{font-size:8px!important;padding:2px 6px!important}.player-scrub-panel{grid-template-columns:1fr;gap:6px}.button-local-message,.storage-inline-help,.upload-loaded-note{font-size:14px!important;padding:9px 10px!important}.bewaar-regel{align-items:center!important}.bewaar-regel button:not(.help-icon){width:100%!important;justify-content:flex-start!important;text-align:left!important}.bewaar-regel .help-icon{width:30px!important;min-width:30px!important;flex-basis:30px!important}}
</style>`;

const APP_SCRIPT = `<script id="coach-extra-ui-script">
(function(){
  function notify(text){ if(typeof window.toonMelding==='function') window.toonMelding(text); }
  function norm(el){ return (el && el.textContent || '').replace(/\s+/g,' ').trim(); }
  function findButton(label, scope){ return Array.prototype.find.call((scope||document).querySelectorAll('button'), function(b){ return norm(b).indexOf(label)!==-1; }); }
  function hasVideo(){ var video=document.getElementById('leerlingVideo'); return !!(video && (video.src || video.srcObject)); }
  function normalizeAi(){ Array.prototype.slice.call(document.querySelectorAll('button,.help-icon,#aiAnalyseVak h3')).forEach(function(el){ if(el.textContent) el.textContent=el.textContent.replace(/Analyseer met AI/g,'Analyseer met Ai'); if(el.dataset && el.dataset.help) el.dataset.help=el.dataset.help.replace(/Analyseer met AI/g,'Analyseer met Ai'); if(el.getAttribute && el.getAttribute('aria-label')) el.setAttribute('aria-label', el.getAttribute('aria-label').replace(/Analyseer met AI/g,'Analyseer met Ai')); }); }
  function wrapHelp(button, help, cls){ if(!button || !help) return; var row=button.closest('.analysis-help-row,.session-help-row'); if(!row){ row=document.createElement('div'); row.className=cls; button.parentNode.insertBefore(row, button); row.appendChild(button); } if(help.parentElement!==row) row.appendChild(help); }
  function layout(){ normalizeAi(); var ai=findButton('Analyseer met Ai'); var aiHelp=Array.prototype.find.call(document.querySelectorAll('button.help-icon'), function(b){ return /Analyseer met A[iI]/.test((b.getAttribute('aria-label')||'')+' '+(b.dataset&&b.dataset.help||'')); }); wrapHelp(ai, aiHelp, 'analysis-help-row'); var skeleton=document.getElementById('skeletonTrackingKnop') || findButton('Start Skeleton Tracking'); if(skeleton && !document.getElementById('skeletonTrackingHelpKnop')){ var h=document.createElement('button'); h.type='button'; h.id='skeletonTrackingHelpKnop'; h.className='help-icon'; h.textContent='?'; h.setAttribute('aria-label','Help Start Skeleton Tracking'); h.setAttribute('data-help','Skeleton Tracking tekent een eenvoudig skelet over de spelersvideo.'); wrapHelp(skeleton,h,'analysis-help-row'); } ['Analyseer met Ai','Start Skeleton Tracking','Automatische houding-analyse'].forEach(function(label){ var b=findButton(label); if(b) b.classList.add('analysis-aligned-button'); }); ['Handmatig moment toevoegen','Sessie Opslaan','Sessie Laden','Download Analyse'].forEach(function(label){ var b=findButton(label); if(b) b.classList.add('session-aligned-button'); }); var saveSess=findButton('Sessie Opslaan'); if(saveSess && saveSess.parentElement) saveSess.parentElement.classList.add('session-action-stack'); var analysis=document.querySelector('.video-analysis-accordion'); if(analysis && !analysis.dataset.userOpened){ analysis.removeAttribute('open'); analysis.addEventListener('toggle', function(){ analysis.dataset.userOpened='1'; }, {once:true}); } var manageTitle=document.getElementById('manageVideosTitle'); if(manageTitle) manageTitle.innerHTML='\ud83d\udcc1 Spelers video\u2019s beheren'; var analyseTitle=document.getElementById('videoAnalyseTitle'); if(analyseTitle) analyseTitle.innerHTML='\ud83c\udfa5 Analyse'; var recHelp=document.querySelector('.player-box .knopgroep.hidden-during-recording .help-icon'); if(recHelp) recHelp.remove(); initScrub(); prepareRecordingButtons(); }
  function initScrub(){ var video=document.getElementById('leerlingVideo'); if(!video || document.getElementById('playerScrubPanel')) return; var wrapper=video.closest('.video-wrapper'); if(!wrapper) return; var panel=document.createElement('div'); panel.id='playerScrubPanel'; panel.className='player-scrub-panel hidden-during-recording'; panel.innerHTML='<span id="playerScrubCurrent" class="player-scrub-time">0:00</span><input id="playerScrubSlider" class="player-scrub-slider" type="range" min="0" max="1000" value="0" step="1" aria-label="Spoel door de spelersvideo"><span id="playerScrubDuration" class="player-scrub-time">0:00</span><div id="aiMarkerLayer" class="ai-marker-layer"></div>'; wrapper.insertAdjacentElement('afterend', panel); }
  function syncScrub(){ var video=document.getElementById('leerlingVideo'), slider=document.getElementById('playerScrubSlider'), current=document.getElementById('playerScrubCurrent'), duration=document.getElementById('playerScrubDuration'); if(!video||!slider||slider.dataset.scrubReady) return; slider.dataset.scrubReady='1'; function fmt(t){ if(!isFinite(t)) t=0; var m=Math.floor(t/60), s=String(Math.floor(t%60)).padStart(2,'0'); return m+':'+s; } function update(){ var d=video.duration||0; if(duration) duration.textContent=fmt(d); if(current) current.textContent=fmt(video.currentTime||0); if(d && document.activeElement!==slider) slider.value=Math.round((video.currentTime/d)*1000); } slider.addEventListener('input',function(){ var d=video.duration||0; if(d) video.currentTime=(Number(slider.value)/1000)*d; update(); }); video.addEventListener('timeupdate',update); video.addEventListener('loadedmetadata',update); video.addEventListener('durationchange',update); update(); }
  function recRow(){ return document.querySelector('.player-box .knopgroep.hidden-during-recording'); }
  function startBtn(){ var row=recRow(); return row && (findButton('Start Opname',row)||findButton('Bekijk opname',row)||findButton('Nieuwe opname',row)||Array.prototype.find.call(row.querySelectorAll('button'),function(b){return String(b.getAttribute('onclick')||'').indexOf('startOpname')!==-1;})); }
  function stopBtn(){ var row=recRow(); return row && (findButton('Stop Opname',row)||findButton('Stop opname',row)||findButton('Nieuwe opname',row)||Array.prototype.find.call(row.querySelectorAll('button'),function(b){return String(b.getAttribute('onclick')||'').indexOf('stopOpname')!==-1;})); }
  function clearBtn(){ var row=recRow(); return row && Array.prototype.find.call(row.querySelectorAll('button'), function(b){ return /Wis spelersvideo/.test(norm(b)) || String(b.getAttribute('onclick')||'').indexOf('wisLeerlingVideo')!==-1; }); }
  function setClear(visible){ var c=clearBtn(); if(!c) return; c.classList.add('recording-clear-button'); c.style.display=visible?'inline-flex':'none'; c.onclick=function(){ if(typeof window.wisLeerlingVideo==='function') return window.wisLeerlingVideo(); }; }
  function setState(state){ var row=recRow(); if(!row) return; row.classList.remove('recording-state-idle','recording-state-recording','recording-state-recorded'); row.classList.add('recording-state-'+state); }
  function prepareRecordingButtons(){ var s=startBtn(), p=stopBtn(), c=clearBtn(); if(s) s.classList.add('recording-start-button'); if(p) p.classList.add('recording-stop-button'); if(c) c.classList.add('recording-clear-button'); if(document.body.classList.contains('camera-open')) setRecording(); else if(hasVideo()) setRecorded(); else setIdle(); }
  function playRecording(){ var v=document.getElementById('leerlingVideo'); if(!v || !v.src){ notify('Neem eerst een video op.'); return; } v.controls=true; v.muted=false; try{ v.currentTime=0; v.play(); v.scrollIntoView({behavior:'smooth',block:'center'}); }catch(e){} }
  function setIdle(){ var s=startBtn(), p=stopBtn(); setState('idle'); setClear(false); if(s){ s.style.display='inline-flex'; s.textContent='\ud83c\udfa5 Nieuwe opname'; s.classList.remove('recording-ready-button'); s.onclick=function(){ if(typeof window.startOpname==='function') return window.startOpname(); }; } if(p){ p.style.display='none'; p.textContent='\u23f9 Stop Opname'; p.classList.remove('recording-new-button'); p.onclick=function(){ if(window.__originalStopOpname) return window.__originalStopOpname(); }; } }
  function setRecording(){ var s=startBtn(), p=stopBtn(); setState('recording'); setClear(false); if(s) s.style.display='none'; if(p){ p.style.display='inline-flex'; p.textContent='\u23f9 Stop opname'; p.classList.remove('recording-new-button'); p.onclick=function(){ if(typeof window.stopOpname==='function') return window.stopOpname(); }; } }
  function setRecorded(){ var s=startBtn(), p=stopBtn(); setState('recorded'); setClear(true); if(s){ s.style.display='inline-flex'; s.textContent='\u25b6 Bekijk opname'; s.classList.add('recording-ready-button'); s.onclick=playRecording; } if(p){ p.style.display='inline-flex'; p.textContent='\ud83c\udfa5 Nieuwe opname'; p.classList.add('recording-new-button'); p.onclick=function(){ if(typeof window.startOpname==='function') return window.startOpname(); }; } }
  function wrapRecording(){ if(window.__recordingButtonStateReady) return; if(typeof window.startOpname!=='function' || typeof window.stopOpname!=='function' || typeof window.wisLeerlingVideo!=='function'){ setTimeout(function(){ wrapRecording(); prepareRecordingButtons(); },250); return; } window.__recordingButtonStateReady=true; window.__originalStartOpname=window.startOpname; window.__originalStopOpname=window.stopOpname; window.__originalWisLeerlingVideo=window.wisLeerlingVideo; window.startOpname=async function(){ var r=await window.__originalStartOpname.apply(this,arguments); setTimeout(setRecording,80); return r; }; window.stopOpname=function(){ var r=window.__originalStopOpname.apply(this,arguments); setTimeout(function(){ setRecorded(); notify('Opname klaar. Speel de video af of maak een nieuwe opname.'); },450); return r; }; window.wisLeerlingVideo=function(){ var r=window.__originalWisLeerlingVideo.apply(this,arguments); setTimeout(setIdle,80); return r; }; prepareRecordingButtons(); }
  function setupStorage(){ var save=Array.prototype.find.call(document.querySelectorAll('button'), function(b){ return /Bewaar video in lijst|Bewaar in deze browser/.test(norm(b)); }); if(save) save.textContent='\ud83d\udcbe Bewaar in deze browser'; if(save && !document.getElementById('downloadCurrentVideoBtn')){ var d=document.createElement('button'); d.id='downloadCurrentVideoBtn'; d.type='button'; d.className='download-video-bestand-knop'; d.textContent='\ud83d\udcc1 Bewaar als bestand'; d.onclick=downloadCurrentVideo; save.insertAdjacentElement('afterend',d); } var uitleg=document.querySelector('.uitleg-video'); if(uitleg){ uitleg.classList.add('storage-choice-note'); uitleg.textContent=''; } }
  function cleanName(name){ return (name||'pickleball-video').trim().replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-') || 'pickleball-video'; }
  function downloadBlob(blob,name){ var url=URL.createObjectURL(blob); var a=document.createElement('a'); a.href=url; a.download=cleanName(name).replace(/\.(webm|mp4|mov)$/i,'')+'.webm'; document.body.appendChild(a); a.click(); setTimeout(function(){ URL.revokeObjectURL(url); a.remove(); },1200); notify('Bestand klaargezet. Hierna kunt u deze video weer uploaden.'); }
  function downloadCurrentVideo(){ var naamInput=document.getElementById('videoNaam'); var naam=(naamInput&&naamInput.value)||'pickleball-video'; try{ if(typeof huidigeVideoBlob!=='undefined' && huidigeVideoBlob){ downloadBlob(huidigeVideoBlob,naam); return; } if(typeof recordedChunks!=='undefined' && recordedChunks && recordedChunks.length){ downloadBlob(new Blob(recordedChunks,{type:typeof huidigeVideoType!=='undefined'?huidigeVideoType:'video/webm'}),naam); return; } notify('Neem eerst een video op of upload een video.'); }catch(e){ notify('Downloaden lukt niet in deze browser.'); } }
  function setupUpload(){ var input=document.getElementById('uploadVideo'); if(!input || input.dataset.uploadEnhanced) return; input.dataset.uploadEnhanced='1'; input.addEventListener('change', function(e){ var file=e.target.files&&e.target.files[0]; if(!file) return; setTimeout(function(){ var nameInput=document.getElementById('videoNaam'); if(nameInput && !nameInput.value) nameInput.value=file.name.replace(/\.[^/.]+$/,''); notify('Video geladen. U kunt hem nu boven bekijken, analyseren of bewaren.'); var v=document.getElementById('leerlingVideo'); if(v){ v.controls=true; v.muted=false; v.scrollIntoView({behavior:'smooth',block:'center'}); } setRecorded(); },100); }); }
  function noVideoText(type){ if(type==='ai') return 'Neem eerst een spelersvideo op of upload een video. Daarna kan Analyseer met Ai automatisch momenten en tips maken.'; if(type==='skeleton') return 'Neem eerst een spelersvideo op of upload een video. Daarna tekent Skeleton Tracking een groen skelet over de speler.'; return 'Neem eerst een spelersvideo op of upload een video. Daarna scant de app houding, balans en beweging.'; }
  function guardVideo(event){ var b=event.target&&event.target.closest?event.target.closest('button'):null; if(!b || hasVideo()) return; var label=norm(b), type=''; if(label.indexOf('Analyseer met Ai')!==-1) type='ai'; if(label.indexOf('Start Skeleton Tracking')!==-1) type='skeleton'; if(label.indexOf('Automatische houding-analyse')!==-1) type='houding'; if(!type) return; event.preventDefault(); event.stopPropagation(); event.stopImmediatePropagation(); var msg=document.createElement('div'); msg.className='button-local-message'; msg.textContent=noVideoText(type); (b.closest('.analysis-help-row')||b).insertAdjacentElement('afterend',msg); setTimeout(function(){ if(msg.parentElement) msg.remove(); },7000); }
  document.addEventListener('click', guardVideo, true);
  function markers(){ var panel=document.getElementById('playerScrubPanel'), slider=document.getElementById('playerScrubSlider'), video=document.getElementById('leerlingVideo'), layer=document.getElementById('aiMarkerLayer'); if(!panel||!slider||!video||!layer||!video.duration) return; layer.innerHTML=''; var pr=panel.getBoundingClientRect(), sr=slider.getBoundingClientRect(), y=sr.top-pr.top+sr.height/2; Array.prototype.slice.call(document.querySelectorAll('.moment-blok')).forEach(function(block,i){ var min=block.querySelector('select[id^="min"]'), sec=block.querySelector('select[id^="sec"]'), opm=block.querySelector('input[id^="opmerking"]'); var seconds=(parseInt(min&&min.value||'0',10)*60)+(parseInt(sec&&sec.value||'0',10)); var left=sr.left-pr.left+Math.max(0,Math.min(1,seconds/video.duration))*sr.width; var m=document.createElement('button'); m.type='button'; m.className='ai-scrub-marker '+(/fout|verkeerd|te laat|te vroeg|niet|mist|corrigeer|verbeter|probleem/i.test(opm&&opm.value||'')?'error':'attention'); m.style.left=left+'px'; m.style.top=y+'px'; m.title='Moment '+(i+1); m.onclick=function(e){ e.preventDefault(); e.stopPropagation(); video.currentTime=seconds; video.pause(); }; layer.appendChild(m); }); }
  function apply(){ layout(); syncScrub(); wrapRecording(); setupStorage(); setupUpload(); prepareRecordingButtons(); requestAnimationFrame(markers); }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded', apply); else apply(); [50,200,800,1600,3200,5000].forEach(function(ms){ setTimeout(apply,ms); }); window.addEventListener('resize', function(){ requestAnimationFrame(markers); }); document.addEventListener('change', function(e){ if(e.target && /^(min|sec|opmerking)/.test(e.target.id||'')) requestAnimationFrame(markers); }, true);
})();
</script>`;

const TITLE_LOGO_MARK = `<span class="brand-title-logo" aria-hidden="true"><svg viewBox="0 0 128 128" focusable="false"><defs><linearGradient id="pcLogoA" x1="20" y1="108" x2="96" y2="18" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#07999a"/><stop offset=".58" stop-color="#67c653"/><stop offset="1" stop-color="#b9e51b"/></linearGradient><linearGradient id="pcLogoB" x1="88" y1="108" x2="112" y2="38" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#5dbd4e"/><stop offset="1" stop-color="#b9e51b"/></linearGradient></defs><path d="M18 108C25 59 57 17 80 31c16 10 26 42 34 77" fill="none" stroke="url(#pcLogoA)" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/><path d="M31 101c18-9 31-21 45-33" fill="none" stroke="#4fbd5d" stroke-width="16" stroke-linecap="round" opacity=".95"/><path d="M106 48v58" fill="none" stroke="url(#pcLogoB)" stroke-width="16" stroke-linecap="round"/><circle cx="106" cy="27" r="13" fill="#aee018"/><circle cx="99" cy="24" r="2.2" fill="#eef7f1"/><circle cx="106" cy="19" r="2.2" fill="#eef7f1"/><circle cx="113" cy="24" r="2.2" fill="#eef7f1"/><circle cx="102" cy="33" r="2.2" fill="#eef7f1"/><circle cx="111" cy="34" r="2.2" fill="#eef7f1"/></svg></span>`;
const TITLE_WITH_LOGO = `<h1 class="brand-title">Pickleball Coach${TITLE_LOGO_MARK}</h1>`;

export const config = { matcher: ['/', '/index.html'] };

export default async function middleware(request) {
  const url = new URL('/index.html', request.url);
  const response = await fetch(url, { cache: 'no-store' });
  let html = await response.text();
  html = html.replace(/<div class="ai-melding">[\s\S]*?<\/div>\s*/, '');
  html = html.replace(/<button class="help-icon" data-help="[^\"]*Start opname[^\"]*" aria-label="Help Start opname">\?<\/button>/g, '');
  html = html.replace(/(<button class="help-icon" data-help=")[^"]*Analyseer met A[iI][^"]*(" aria-label="Help Analyseer met A[iI]">\?<\/button>)/, '$1Analyseer met Ai maakt automatisch momenten aan op basis van Ai-tijdcodes en geeft techniek-tips bij de video.$2');
  html = html.replace(/onclick="analyseerMetAI\(\)"/g, 'onclick="if(!window.coachGuardVideoAction||window.coachGuardVideoAction(this,\'ai\')) analyseerMetAI()"');
  html = html.replace(/onclick="toggleSkeletonTracking\(\)"/g, 'onclick="if(!window.coachGuardVideoAction||window.coachGuardVideoAction(this,\'skeleton\')) toggleSkeletonTracking()"');
  html = html.replace(/onclick="analyseerMetMediaPipe\(\)"/g, 'onclick="if(!window.coachGuardVideoAction||window.coachGuardVideoAction(this,\'houding\')) analyseerMetMediaPipe()"');
  html = html.replace(/Analyseer met AI/g, 'Analyseer met Ai');
  html = html.replace(/AI-tijdcodes/g, 'Ai-tijdcodes');
  if (!html.includes('coach-layout-polish-style')) html = html.replace('</head>', `${LAYOUT_STYLE}\n</head>`);
  if (!html.includes('coach-extra-ui-script')) html = html.replace('</body>', `${APP_SCRIPT}\n</body>`);
  if (!html.includes('<h1 class="brand-title">')) html = html.replace(/<h1[^>]*>\s*Pickleball Coach\s*<\/h1>/, TITLE_WITH_LOGO);
  return new Response(html, { status: response.ok ? 200 : response.status, headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-cache, no-store, must-revalidate' } });
}
